steps:
  - label: Linux build
    command: |
      ./prepare-linux.sh
      ./build-linux.sh
      ./post-linux.sh
    agents:
      queue: linux
  - label: OSX build
    command: |
      ./prepare-osx.sh
      ./build-osx.sh
      ./post-osx.sh
    agents:
      queue: osx