steps:
  - label: Linux prepare
    command: ./prepare-linux.sh
    agents:
      queue: linux
  - wait
  - label: Linux build 
    command: ./build-linux.sh
    agents:
      queue: linux
  - wait: ~
    continue_on_failure: true
  - label: Linux post build
    command: ./post-linux.sh
    agents:
      queue: linux
